package com.yaohua.love.db;

import com.yaohua.love.db.TCustomer;

import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface TCustomerMapper extends Mapper<TCustomer>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUSTOMER
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	int insert(TCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_CUSTOMER
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	List<TCustomer> selectAll();
}