package com.yaohua.love.db;

import java.util.Date;

import javax.persistence.Id;

import com.yaohua.love.util.UUIdGenId;

import tk.mybatis.mapper.annotation.KeySql;

public class TCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	@Id
    @KeySql(genId = UUIdGenId.class)
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.CREATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.CREATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private Long createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.EMAIL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String emailFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.IMAGE
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.IS_DELETED
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.NAME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.SID_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String sidFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.TEL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private String telFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.UPDATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.UPDATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private Long updaterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_CUSTOMER.USER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	private Long userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.ID
	 * @return  the value of T_CUSTOMER.ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.ID
	 * @param id  the value for T_CUSTOMER.ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.CREATE_TIME
	 * @return  the value of T_CUSTOMER.CREATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.CREATE_TIME
	 * @param createTime  the value for T_CUSTOMER.CREATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.CREATER_ID
	 * @return  the value of T_CUSTOMER.CREATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Long getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.CREATER_ID
	 * @param createrId  the value for T_CUSTOMER.CREATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setCreaterId(Long createrId) {
		this.createrId = createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.EMAIL_FLAG
	 * @return  the value of T_CUSTOMER.EMAIL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getEmailFlag() {
		return emailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.EMAIL_FLAG
	 * @param emailFlag  the value for T_CUSTOMER.EMAIL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setEmailFlag(String emailFlag) {
		this.emailFlag = emailFlag == null ? null : emailFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.IMAGE
	 * @return  the value of T_CUSTOMER.IMAGE
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.IMAGE
	 * @param image  the value for T_CUSTOMER.IMAGE
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.IS_DELETED
	 * @return  the value of T_CUSTOMER.IS_DELETED
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.IS_DELETED
	 * @param isDeleted  the value for T_CUSTOMER.IS_DELETED
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted == null ? null : isDeleted.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.NAME
	 * @return  the value of T_CUSTOMER.NAME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.NAME
	 * @param name  the value for T_CUSTOMER.NAME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.SID_FLAG
	 * @return  the value of T_CUSTOMER.SID_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getSidFlag() {
		return sidFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.SID_FLAG
	 * @param sidFlag  the value for T_CUSTOMER.SID_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setSidFlag(String sidFlag) {
		this.sidFlag = sidFlag == null ? null : sidFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.TEL_FLAG
	 * @return  the value of T_CUSTOMER.TEL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public String getTelFlag() {
		return telFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.TEL_FLAG
	 * @param telFlag  the value for T_CUSTOMER.TEL_FLAG
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setTelFlag(String telFlag) {
		this.telFlag = telFlag == null ? null : telFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.UPDATE_TIME
	 * @return  the value of T_CUSTOMER.UPDATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.UPDATE_TIME
	 * @param updateTime  the value for T_CUSTOMER.UPDATE_TIME
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.UPDATER_ID
	 * @return  the value of T_CUSTOMER.UPDATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Long getUpdaterId() {
		return updaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.UPDATER_ID
	 * @param updaterId  the value for T_CUSTOMER.UPDATER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setUpdaterId(Long updaterId) {
		this.updaterId = updaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_CUSTOMER.USER_ID
	 * @return  the value of T_CUSTOMER.USER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_CUSTOMER.USER_ID
	 * @param userId  the value for T_CUSTOMER.USER_ID
	 * @mbg.generated  Sun Dec 22 22:09:53 CST 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
}