package com.yaohua.love.db;

import com.yaohua.love.db.TUser;

import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Mon Dec 23 21:44:25 CST 2019
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Mon Dec 23 21:44:25 CST 2019
     */
    List<TUser> selectAll();
    
    TUser selectByPrimaryKey(TUser u);
}